name: 添加项目 / Add Proejct
description: 将你的项目添加到 UIGF 网站中 / Add your project to uigf.org
title: "[Project Registration]: Project Name"
labels: ["Project Registration"]
assignees:
  - Masterain98
body:
  - type: markdown
    attributes:
      value: |
        请填写下面的表单 / Fill the form below

  - type: dropdown
    id: standard selection
    attributes:
      label: Standard
      description: Select standard you are using in your project
      options:
       - UIGF 
       - UIAF
       - SRGF
    validations:
      required: true

  - type: textarea
    id: sample-output
    attributes:
      label: Sample Output
      description: Upload a sample JSON output of data from your project using target standard.
    validations:
      required: true