name: Artifact Rating Rules
about: 圣遗物评分细则建议
title: "[Artifact Rating] 请在这里填写角色名称"
labels: area-AvatarInfo
assignees: Lightczx

body:
  - type: markdown
    attributes:
    value: |
      请按下方的要求填写完整的问题表单
        
  - type: textarea
    id: what-happened
    attributes:
      label: 评分细则
      description: 请修改下方表格中的**角色名称**和**各属性权重**，并在表格后添加合适的说明
      value: |
        |项目|评分占比(0-100)|
        |-----|-----|
        |角色名称| 旅行者 |
        |生命值%|  10% |
        |攻击力%|  10% |
        |防御力%|  10% |
        |暴击率|  10% |
        |暴击伤害|  10% |
        |元素精通||  10% |
        |充能效率|  10% |
        |治疗加成|  10% |
        |元素伤害|  10% |
    validations:
      required: true
