name: 圣遗物评分细则建议
description: 为圣遗物评分规则提供你的想法
title: "[Artifact Rating] 请在这里填写角色名称"
labels: area-AvatarInfo
assignees: Lightczx

body:
 - type: markdown
   attributes:
    value: |
      请按下方的要求填写完整的问题表单
        
 - type: textarea
   id: your-suggested-rule
   attributes:
    label: 评分细则
    description: |
     请修改下方表格中的**角色名称**和**各属性权重**，并在表格后添加合适的说明
     你可以点击预览按钮（preview）来查看表格最终会显示出的内容
    value: |
        |项目|评分权重(0-100)|
        |-----|-----|
        |角色名称| 旅行者 |
        |生命值|  10 |
        |攻击力|  10 |
        |防御力|  10 |
        |暴击率|  10 |
        |暴击伤害|  10 |
        |元素精通|  10 |
        |充能效率|  10 |
        |治疗加成|  10 |
        |元素伤害|  10 |
   validations:
    required: true
    
 - type: dropdown
   id: no-duplicated-dropdown
   attributes:
     label: 我确认当前没有其它的该角色的圣遗物评分细则建议
     description: 如果有，你应该在已有的工单内回复以提出你的建议
     options:
      - 否
      - 是
   validations:
     required: true

 - type: dropdown
   id: title-filled-dropdown
   attributes:
     label: 我确认已设置合适的标题
     options:
      - 否
      - 是
   validations:
     required: true
     
 - type: dropdown
   id: all-filled-dropdown
   attributes:
     label: 我确认已完整填写表格
     options:
      - 否
      - 是
   validations:
     required: true
