blank_issues_enabled: false
contact_links:
  - name: Snap Hutao 官方文档 / Snap Hutao Document
    url: https://hut.ao
    about: 请在提出问题前阅读文档 / Read the document before submit the issue
  
  - name: 常见问题 / FAQ
    url: https://hut.ao/advanced/FAQ.html
  
  - name: 常见程序异常 / Common Program Exceptions
    url: https://hut.ao/advanced/exceptions.html
    