name: Feature Request 功能请求 
description: Tell us about your thought 告诉我们你的想法
title: "[Feat]: Place your title here 在这里填写一个合适的标题"
labels: ["功能", "priority:none"]
assignees:
  - Lightczx
body:
  - type: markdown
    attributes:
      value: |
        Please fill the form below
        请按下方的要求填写完整的问题表单。

  - type: textarea
    id: back
    attributes:
      label: Background & Motivation 背景与动机
      description: Reason why this feature is needed. If multiple features is requested, please open multiple issues for each of them. 添加此功能的理由，如果你想要实现多个功能，请分别发起多个单独的 Issue
    validations:
      required: true

  - type: textarea
    id: req
    attributes:
      label: Detail of the Feature 想要实现或优化的功能
      description: Descripbe the feaure in detail. The more detailed and convincing the desciprtion the more likyly feature will be accepted. 详细的描述一下你想要的功能，描述的越具体，采纳的可能性越高
    validations:
      required: true